### ISSUE TITLE
Details?

### ISSUE THREAD

**Issue by aerenchyma** [bjin02/SI507-FinalProject#1]
You've reflected all the requirements and showing which visualization system you are interested in, but all other details about the project are missing, which makes it impossible to give feedback!

**Comment by bjin02** [comment]
Hi Jackie,
I will add more details tonight. Would you mind checking it again after I finished? Hope it won't influence my project 6 grade.Thanks!

**Comment by bjin02** [comment]
@aerenchyma  I have update and commit more details to the README file. Feel free to review again and comment here.Thanks!

**Comment by anandpdoshi** [comment]
@bjin02 Your project is doing almost the same things as Project 6. Please have a look at this: https://paper.dropbox.com/doc/SI-507-Fall-2017-Final-Project-XwIGPUCZrTaBNTT75uU4B#:uid=717111457109464449000378&h2=Note — You have to do something different than what has been done in class and sections, like using a different data source, or using different data from the same source. The project should have additional effort involved than just copy pasting existing code that was covered in the section and class.

**Comment by bjin02** [comment]
@aerenchyma @anandpdoshi  I have made the change from the National Park data to the Tumblr Post data per your feedback. Please review and give me some feedback. Thanks!

**Comment by bjin02** [comment]
@anandpdoshi hi can you have a quick look and check if the new update is ok? Thanks!

**Comment by bjin02** [comment]
Milestones, Issues have been added

**Comment by anandpdoshi** [comment]
@bjin02 you can go ahead with using Tumblr
